/*
 * Generated by rocket-ts 0.1.0 🚀 🌎
 */
export interface k7 {
	// main.rs
	// handler "/deliver"
	deliver: (DeliveryRequest) => any;
	// handler "/track/<package_id>"
	track: (package_id:String) => any;
	// handler "/packages/destination/<destination>"
	packages_by_destination: (destination:String) => any;
	// handler "/packages/speed/<speed>"
	packages_by_speed: (speed:String) => any;
	// handler "/packages/count"
	package_count: () => any;
}
